### ISSUE TITLE
How to retrieve Twitter ID

### ISSUE THREAD

**Issue by winbotscript** [xrths/COVID19-France#11]
Hello there,

May i ask, how to get preview_id for twitter account ? cause at gettwitterid.com i can't find it

Help me please

Regards,

WinBot

**Comment by thomas-rx** [comment]
Hello,

**Just search on google "twitter id"** and take one of the first sites. The goal of the manipulation is to retrieve the twitter account id of the owner who will be informed when the bot posts a tweet.

Hoping to have helped you. 

_Thomas_
